"""add payment audit metadata

Revision ID: 2a408bf8badb
Revises: e124ed32b079
Create Date: 2026-08-26 06:31:03.010843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a408bf8badb'
down_revision: Union[str, None] = 'e124ed32b079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_events', sa.Column('actor_user_id', sa.Integer(), nullable=True))
    op.add_column('payment_events', sa.Column('metadata', sa.JSON(), nullable=True))
    op.create_foreign_key(
       'fk_payment_events_actor_user',
       'payment_events',
       'users',
       ['actor_user_id'],
       ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
       'fk_payment_events_actor_user',
       'payment_events',
        type_='foreignkey'
    )
    op.drop_column('payment_events', 'metadata')
    op.drop_column('payment_events', 'actor_user_id')
    # ### end Alembic commands ###
