"""add product stock quantity

Revision ID: 3105be9533db
Revises: b8c2d1e4f6a7
Create Date: 2026-08-24 06:10:29.297887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3105be9533db'
down_revision: Union[str, None] = 'b8c2d1e4f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
	    'products',
	    sa.Column('stock_quantity', sa.Integer(), nullable=False, server_default='0')
	)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_quantity')
    # ### end Alembic commands ###
